### ISSUE TITLE
Resending verification emails

### ISSUE THREAD

**Issue by TorrentofShame** [KnightHacks/hackathon-2021-backend#85]
Should not have to authenticate to resend verification emails. However, should rate limit (or psuedo rate-limit) to prevent spamming)

## tasks
- [ ] Unauth resending ver emails
- [ ] rate limit resending ver emails
- [ ] include link to resend in ver email template
- [ ] automatically resend on failed ver (if expired)
